### ISSUE TITLE
*

### ISSUE THREAD

**Issue by demining** [chrisvwx/LLLplus.jl#58]
****

**Comment by chrisvwx** [comment]
Not an issue or a topic that is otherwise relevant to this repo.  

For my own reference, the same question was asked in many other repos ([1](https://www.federalreserve.gov/newsevents/pressreleases/files/bcreg20211123a1.pdf), [2](https://github.com/MiBu84/Hybrid-Attack-binary-LWE/issues/1), [3](https://github.com/PhiQuadro/Lattice_attacks_on_RSA/issues/1) for example).
